"""
Full Unicode emoji set organised into Discord-style categories.
Each entry: (emoji_char, descriptive_name)  — name is used for search.
"""

EMOJI_DATA = {

    # ─────────────────────────────────────────────────────────────────────────
    "😀 Smileys & Emotion": [
        # face-smiling
        ("😀", "grinning face"),
        ("😃", "grinning face with big eyes"),
        ("😄", "grinning face with smiling eyes"),
        ("😁", "beaming face with smiling eyes"),
        ("😆", "grinning squinting face"),
        ("😅", "grinning face with sweat"),
        ("🤣", "rolling on the floor laughing"),
        ("😂", "face with tears of joy"),
        ("🙂", "slightly smiling face"),
        ("🙃", "upside-down face"),
        ("🫠", "melting face"),
        ("😉", "winking face"),
        ("😊", "smiling face with smiling eyes"),
        ("😇", "smiling face with halo"),
        # face-affection
        ("🥰", "smiling face with hearts"),
        ("😍", "smiling face with heart-eyes"),
        ("🤩", "star-struck"),
        ("😘", "face blowing a kiss"),
        ("😗", "kissing face"),
        ("☺️", "smiling face"),
        ("😚", "kissing face with closed eyes"),
        ("😙", "kissing face with smiling eyes"),
        ("🥲", "smiling face with tear"),
        # face-tongue
        ("😋", "face savoring food"),
        ("😛", "face with tongue"),
        ("😜", "winking face with tongue"),
        ("🤪", "zany face"),
        ("😝", "squinting face with tongue"),
        ("🤑", "money-mouth face"),
        # face-hand
        ("🤗", "smiling face with open hands"),
        ("🤭", "face with hand over mouth"),
        ("🫢", "face with open eyes and hand over mouth"),
        ("🫣", "face with peeking eye"),
        ("🤫", "shushing face"),
        ("🤔", "thinking face"),
        ("🫡", "saluting face"),
        # face-neutral-skeptical
        ("🤐", "zipper-mouth face"),
        ("🤨", "face with raised eyebrow"),
        ("😐", "neutral face"),
        ("😑", "expressionless face"),
        ("😶", "face without mouth"),
        ("🫥", "dotted line face"),
        ("😶‍🌫️", "face in clouds"),
        ("😏", "smirking face"),
        ("😒", "unamused face"),
        ("🙄", "face with rolling eyes"),
        ("😬", "grimacing face"),
        ("😮‍💨", "face exhaling"),
        ("🤥", "lying face"),
        ("🫨", "shaking face"),
        # face-sleepy
        ("😌", "relieved face"),
        ("😔", "pensive face"),
        ("😪", "sleepy face"),
        ("🤤", "drooling face"),
        ("😴", "sleeping face"),
        # face-unwell
        ("😷", "face with medical mask"),
        ("🤒", "face with thermometer"),
        ("🤕", "face with head-bandage"),
        ("🤢", "nauseated face"),
        ("🤮", "face vomiting"),
        ("🤧", "sneezing face"),
        ("🥵", "hot face"),
        ("🥶", "cold face"),
        ("🥴", "woozy face"),
        ("😵", "face with crossed-out eyes"),
        ("😵‍💫", "face with spiral eyes"),
        ("🤯", "exploding head"),
        # face-hat
        ("🤠", "cowboy hat face"),
        ("🥳", "partying face"),
        ("🥸", "disguised face"),
        # face-glasses
        ("😎", "smiling face with sunglasses"),
        ("🤓", "nerd face"),
        ("🧐", "face with monocle"),
        # face-concerned
        ("😕", "confused face"),
        ("🫤", "face with diagonal mouth"),
        ("😟", "worried face"),
        ("🙁", "slightly frowning face"),
        ("☹️", "frowning face"),
        ("😮", "face with open mouth"),
        ("😯", "hushed face"),
        ("😲", "astonished face"),
        ("😳", "flushed face"),
        ("🥺", "pleading face"),
        ("🥹", "face holding back tears"),
        ("😦", "frowning face with open mouth"),
        ("😧", "anguished face"),
        ("😨", "fearful face"),
        ("😰", "anxious face with sweat"),
        ("😥", "sad but relieved face"),
        ("😢", "crying face"),
        ("😭", "loudly crying face"),
        ("😱", "face screaming in fear"),
        ("😖", "confounded face"),
        ("😣", "persevering face"),
        ("😞", "disappointed face"),
        ("😓", "downcast face with sweat"),
        ("😩", "weary face"),
        ("😫", "tired face"),
        ("🥱", "yawning face"),
        # face-negative
        ("😤", "face with steam from nose"),
        ("😡", "enraged face"),
        ("😠", "angry face"),
        ("🤬", "face with symbols on mouth"),
        ("😈", "smiling face with horns"),
        ("👿", "angry face with horns"),
        ("💀", "skull"),
        ("☠️", "skull and crossbones"),
        # face-costume
        ("💩", "pile of poo"),
        ("🤡", "clown face"),
        ("👹", "ogre"),
        ("👺", "goblin"),
        ("👻", "ghost"),
        ("👽", "alien"),
        ("👾", "alien monster"),
        ("🤖", "robot"),
        # cat-face
        ("😺", "grinning cat"),
        ("😸", "grinning cat with smiling eyes"),
        ("😹", "cat with tears of joy"),
        ("😻", "smiling cat with heart-eyes"),
        ("😼", "cat with wry smile"),
        ("😽", "kissing cat"),
        ("🙀", "weary cat"),
        ("😿", "crying cat"),
        ("😾", "pouting cat"),
        # monkey-face
        ("🙈", "see-no-evil monkey"),
        ("🙉", "hear-no-evil monkey"),
        ("🙊", "speak-no-evil monkey"),
        # hearts
        ("💌", "love letter"),
        ("💘", "heart with arrow"),
        ("💝", "heart with ribbon"),
        ("💖", "sparkling heart"),
        ("💗", "growing heart"),
        ("💓", "beating heart"),
        ("💞", "revolving hearts"),
        ("💕", "two hearts"),
        ("💟", "heart decoration"),
        ("❣️", "heart exclamation"),
        ("💔", "broken heart"),
        ("❤️‍🔥", "heart on fire"),
        ("❤️‍🩹", "mending heart"),
        ("❤️", "red heart"),
        ("🩷", "pink heart"),
        ("🧡", "orange heart"),
        ("💛", "yellow heart"),
        ("💚", "green heart"),
        ("💙", "blue heart"),
        ("🩵", "light blue heart"),
        ("💜", "purple heart"),
        ("🤎", "brown heart"),
        ("🖤", "black heart"),
        ("🩶", "grey heart"),
        ("🤍", "white heart"),
        # emotion
        ("💋", "kiss mark"),
        ("💯", "hundred points"),
        ("💢", "anger symbol"),
        ("💥", "collision"),
        ("💫", "dizzy"),
        ("💦", "sweat droplets"),
        ("💨", "dashing away"),
        ("🕳️", "hole"),
        ("💬", "speech balloon"),
        ("👁️‍🗨️", "eye in speech bubble"),
        ("🗨️", "left speech bubble"),
        ("🗯️", "right anger bubble"),
        ("💭", "thought balloon"),
        ("💤", "zzz"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "🧑 People & Body": [
        # hand-fingers-open
        ("👋", "waving hand"),
        ("🤚", "raised back of hand"),
        ("🖐️", "hand with fingers splayed"),
        ("✋", "raised hand"),
        ("🖖", "vulcan salute"),
        ("🫱", "rightwards hand"),
        ("🫲", "leftwards hand"),
        ("🫳", "palm down hand"),
        ("🫴", "palm up hand"),
        ("🫷", "leftwards pushing hand"),
        ("🫸", "rightwards pushing hand"),
        # hand-fingers-partial
        ("👌", "ok hand"),
        ("🤌", "pinched fingers"),
        ("🤏", "pinching hand"),
        ("✌️", "victory hand"),
        ("🤞", "crossed fingers"),
        ("🫰", "hand with index finger and thumb crossed"),
        ("🤟", "love-you gesture"),
        ("🤘", "sign of the horns"),
        ("🤙", "call me hand"),
        # hand-single-finger
        ("👈", "backhand index pointing left"),
        ("👉", "backhand index pointing right"),
        ("👆", "backhand index pointing up"),
        ("🖕", "middle finger"),
        ("👇", "backhand index pointing down"),
        ("☝️", "index pointing up"),
        ("🫵", "index pointing at the viewer"),
        # hand-fingers-closed
        ("👍", "thumbs up"),
        ("👎", "thumbs down"),
        ("✊", "raised fist"),
        ("👊", "oncoming fist"),
        ("🤛", "left-facing fist"),
        ("🤜", "right-facing fist"),
        # hands
        ("👏", "clapping hands"),
        ("🙌", "raising hands"),
        ("🫶", "heart hands"),
        ("👐", "open hands"),
        ("🤲", "palms up together"),
        ("🤝", "handshake"),
        ("🙏", "folded hands"),
        # hand-prop
        ("✍️", "writing hand"),
        ("💅", "nail polish"),
        ("🤳", "selfie"),
        # body-parts
        ("💪", "flexed biceps"),
        ("🦾", "mechanical arm"),
        ("🦿", "mechanical leg"),
        ("🦵", "leg"),
        ("🦶", "foot"),
        ("👂", "ear"),
        ("🦻", "ear with hearing aid"),
        ("👃", "nose"),
        ("🫀", "anatomical heart"),
        ("🫁", "lungs"),
        ("🧠", "brain"),
        ("🦷", "tooth"),
        ("🦴", "bone"),
        ("👀", "eyes"),
        ("👁️", "eye"),
        ("👅", "tongue"),
        ("👄", "mouth"),
        ("🫦", "biting lip"),
        # person
        ("👶", "baby"),
        ("🧒", "child"),
        ("👦", "boy"),
        ("👧", "girl"),
        ("🧑", "person"),
        ("👱", "person blond hair"),
        ("👨", "man"),
        ("🧔", "person beard"),
        ("👩", "woman"),
        ("🧓", "older person"),
        ("👴", "old man"),
        ("👵", "old woman"),
        # person-gesture
        ("🙍", "person frowning"),
        ("🙎", "person pouting"),
        ("🙅", "person gesturing no"),
        ("🙆", "person gesturing ok"),
        ("💁", "person tipping hand"),
        ("🙋", "person raising hand"),
        ("🧏", "deaf person"),
        ("🙇", "person bowing"),
        ("🤦", "person facepalming"),
        ("🤷", "person shrugging"),
        # person-role
        ("👮", "police officer"),
        ("🕵️", "detective"),
        ("💂", "guard"),
        ("🥷", "ninja"),
        ("👷", "construction worker"),
        ("🫅", "person with crown"),
        ("🤴", "prince"),
        ("👸", "princess"),
        ("👳", "person wearing turban"),
        ("👲", "person with skullcap"),
        ("🧕", "woman with headscarf"),
        ("🤵", "person in tuxedo"),
        ("👰", "person with veil"),
        ("🤰", "pregnant woman"),
        ("🫃", "pregnant man"),
        ("🫄", "pregnant person"),
        ("🤱", "breast-feeding"),
        ("👼", "baby angel"),
        # person-fantasy
        ("🎅", "santa claus"),
        ("🤶", "mrs claus"),
        ("🧑‍🎄", "mx claus"),
        ("🦸", "superhero"),
        ("🦹", "supervillain"),
        ("🧙", "mage"),
        ("🧝", "elf"),
        ("🧛", "vampire"),
        ("🧟", "zombie"),
        ("🧞", "genie"),
        ("🧜", "merperson"),
        ("🧚", "fairy"),
        ("🧌", "troll"),
        # person-activity
        ("🚶", "person walking"),
        ("🧍", "person standing"),
        ("🧎", "person kneeling"),
        ("🧑‍🦯", "person with white cane"),
        ("🧑‍🦼", "person in motorized wheelchair"),
        ("🧑‍🦽", "person in manual wheelchair"),
        ("🏃", "person running"),
        ("💃", "woman dancing"),
        ("🕺", "man dancing"),
        ("🕴️", "person in suit levitating"),
        ("👯", "people with bunny ears"),
        ("🧖", "person in steamy room"),
        ("🧗", "person climbing"),
        # person-sport
        ("🤺", "person fencing"),
        ("🏇", "horse racing"),
        ("⛷️", "skier"),
        ("🏂", "snowboarder"),
        ("🏌️", "person golfing"),
        ("🏄", "person surfing"),
        ("🚣", "person rowing boat"),
        ("🧘", "person in lotus position"),
        ("🏊", "person swimming"),
        ("🤽", "person playing water polo"),
        ("🚴", "person biking"),
        ("🏋️", "person lifting weights"),
        ("🤸", "person cartwheeling"),
        ("🤼", "people wrestling"),
        ("🤾", "person playing handball"),
        ("🏆", "trophy"),
        # family
        ("👫", "woman and man holding hands"),
        ("👬", "men holding hands"),
        ("👭", "women holding hands"),
        ("💏", "kiss"),
        ("💑", "couple with heart"),
        ("👪", "family"),
        # person-symbol
        ("🗣️", "speaking head"),
        ("👤", "bust in silhouette"),
        ("👥", "busts in silhouette"),
        ("🫂", "people hugging"),
        ("👣", "footprints"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "🐶 Animals & Nature": [
        # animal-mammal
        ("🐶", "dog face"),
        ("🐱", "cat face"),
        ("🐭", "mouse face"),
        ("🐹", "hamster"),
        ("🐰", "rabbit face"),
        ("🦊", "fox"),
        ("🐻", "bear"),
        ("🐼", "panda"),
        ("🐻‍❄️", "polar bear"),
        ("🐨", "koala"),
        ("🐯", "tiger face"),
        ("🦁", "lion"),
        ("🐮", "cow face"),
        ("🐷", "pig face"),
        ("🐽", "pig nose"),
        ("🐸", "frog"),
        ("🐵", "monkey face"),
        ("🐔", "chicken"),
        ("🐧", "penguin"),
        ("🐦", "bird"),
        ("🐦‍🔥", "phoenix"),
        ("🐤", "baby chick"),
        ("🐣", "hatching chick"),
        ("🐥", "front-facing baby chick"),
        ("🦆", "duck"),
        ("🦅", "eagle"),
        ("🦉", "owl"),
        ("🦇", "bat"),
        ("🐺", "wolf"),
        ("🐗", "boar"),
        ("🐴", "horse face"),
        ("🦄", "unicorn"),
        ("🐝", "honeybee"),
        ("🪱", "worm"),
        ("🐛", "bug"),
        ("🦋", "butterfly"),
        ("🐌", "snail"),
        ("🐞", "lady beetle"),
        ("🐜", "ant"),
        ("🪲", "beetle"),
        ("🦟", "mosquito"),
        ("🪰", "fly"),
        ("🪳", "cockroach"),
        ("🦂", "scorpion"),
        ("🐢", "turtle"),
        ("🐍", "snake"),
        ("🦎", "lizard"),
        ("🦖", "t-rex"),
        ("🦕", "sauropod"),
        ("🐊", "crocodile"),
        ("🐅", "tiger"),
        ("🐆", "leopard"),
        ("🦓", "zebra"),
        ("🦍", "gorilla"),
        ("🦧", "orangutan"),
        ("🦣", "mammoth"),
        ("🐘", "elephant"),
        ("🦛", "hippopotamus"),
        ("🦏", "rhinoceros"),
        ("🐪", "camel"),
        ("🐫", "two-hump camel"),
        ("🦒", "giraffe"),
        ("🦘", "kangaroo"),
        ("🦬", "bison"),
        ("🐃", "water buffalo"),
        ("🐂", "ox"),
        ("🐄", "cow"),
        ("🐎", "horse"),
        ("🐖", "pig"),
        ("🐏", "ram"),
        ("🐑", "ewe"),
        ("🦙", "llama"),
        ("🐐", "goat"),
        ("🦌", "deer"),
        ("🦬", "bison"),
        ("🐕", "dog"),
        ("🐩", "poodle"),
        ("🦮", "guide dog"),
        ("🐕‍🦺", "service dog"),
        ("🐈", "cat"),
        ("🐈‍⬛", "black cat"),
        ("🪶", "feather"),
        ("🐓", "rooster"),
        ("🦃", "turkey"),
        ("🦤", "dodo"),
        ("🦚", "peacock"),
        ("🦜", "parrot"),
        ("🦢", "swan"),
        ("🦩", "flamingo"),
        ("🕊️", "dove"),
        ("🐇", "rabbit"),
        ("🦝", "raccoon"),
        ("🦨", "skunk"),
        ("🦡", "badger"),
        ("🦫", "beaver"),
        ("🦦", "otter"),
        ("🦥", "sloth"),
        ("🐁", "mouse"),
        ("🐀", "rat"),
        ("🐿️", "chipmunk"),
        ("🦔", "hedgehog"),
        # animal-marine
        ("🐳", "spouting whale"),
        ("🐋", "whale"),
        ("🐬", "dolphin"),
        ("🦭", "seal"),
        ("🐟", "fish"),
        ("🐠", "tropical fish"),
        ("🐡", "blowfish"),
        ("🦈", "shark"),
        ("🐙", "octopus"),
        ("🐚", "spiral shell"),
        ("🪸", "coral"),
        ("🐌", "snail"),
        ("🦀", "crab"),
        ("🦞", "lobster"),
        ("🦐", "shrimp"),
        ("🦑", "squid"),
        ("🪼", "jellyfish"),
        # plant-flower
        ("💐", "bouquet"),
        ("🌸", "cherry blossom"),
        ("💮", "white flower"),
        ("🪷", "lotus"),
        ("🏵️", "rosette"),
        ("🌹", "rose"),
        ("🥀", "wilted flower"),
        ("🌺", "hibiscus"),
        ("🌻", "sunflower"),
        ("🌼", "blossom"),
        ("🌷", "tulip"),
        ("🪻", "hyacinth"),
        # plant-other
        ("🌱", "seedling"),
        ("🪴", "potted plant"),
        ("🌲", "evergreen tree"),
        ("🌳", "deciduous tree"),
        ("🌴", "palm tree"),
        ("🌵", "cactus"),
        ("🌾", "sheaf of rice"),
        ("🍄", "mushroom"),
        ("🍁", "maple leaf"),
        ("🍂", "fallen leaf"),
        ("🍃", "leaf fluttering in wind"),
        ("🪺", "nest with eggs"),
        ("🪹", "empty nest"),
        ("🪨", "rock"),
        ("🪵", "wood"),
        # sky & weather
        ("🌍", "globe showing europe-africa"),
        ("🌎", "globe showing americas"),
        ("🌏", "globe showing asia-australia"),
        ("🌐", "globe with meridians"),
        ("🗺️", "world map"),
        ("🌋", "volcano"),
        ("⛰️", "mountain"),
        ("🏔️", "snow-capped mountain"),
        ("🗻", "mount fuji"),
        ("🏕️", "camping"),
        ("🏖️", "beach with umbrella"),
        ("🏜️", "desert"),
        ("🏝️", "desert island"),
        ("🏞️", "national park"),
        ("☀️", "sun"),
        ("🌤️", "sun behind small cloud"),
        ("⛅", "sun behind cloud"),
        ("🌥️", "sun behind large cloud"),
        ("🌦️", "sun behind rain cloud"),
        ("🌧️", "cloud with rain"),
        ("⛈️", "cloud with lightning and rain"),
        ("🌩️", "cloud with lightning"),
        ("🌨️", "cloud with snow"),
        ("❄️", "snowflake"),
        ("⛄", "snowman without snow"),
        ("☃️", "snowman"),
        ("🌬️", "wind face"),
        ("💨", "dashing away"),
        ("🌀", "cyclone"),
        ("🌈", "rainbow"),
        ("🌂", "closed umbrella"),
        ("☂️", "umbrella"),
        ("☔", "umbrella with rain drops"),
        ("⚡", "high voltage"),
        ("🌊", "water wave"),
        ("💧", "droplet"),
        ("💦", "sweat droplets"),
        ("🫧", "bubbles"),
        ("🌙", "crescent moon"),
        ("🌛", "first quarter moon face"),
        ("🌜", "last quarter moon face"),
        ("🌚", "new moon face"),
        ("🌝", "full moon face"),
        ("🌞", "sun with face"),
        ("🪐", "ringed planet"),
        ("⭐", "star"),
        ("🌟", "glowing star"),
        ("💫", "dizzy"),
        ("✨", "sparkles"),
        ("🌠", "shooting star"),
        ("🔥", "fire"),
        ("🌪️", "tornado"),
        ("🌫️", "fog"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "🍕 Food & Drink": [
        # food-fruit
        ("🍇", "grapes"),
        ("🍈", "melon"),
        ("🍉", "watermelon"),
        ("🍊", "tangerine"),
        ("🍋", "lemon"),
        ("🍌", "banana"),
        ("🍍", "pineapple"),
        ("🥭", "mango"),
        ("🍎", "red apple"),
        ("🍏", "green apple"),
        ("🍐", "pear"),
        ("🍑", "peach"),
        ("🍒", "cherries"),
        ("🍓", "strawberry"),
        ("🫐", "blueberries"),
        ("🥝", "kiwi fruit"),
        ("🍅", "tomato"),
        ("🫒", "olive"),
        ("🥥", "coconut"),
        # food-vegetable
        ("🥑", "avocado"),
        ("🍆", "eggplant"),
        ("🥔", "potato"),
        ("🥕", "carrot"),
        ("🌽", "ear of corn"),
        ("🌶️", "hot pepper"),
        ("🫑", "bell pepper"),
        ("🥒", "cucumber"),
        ("🥬", "leafy green"),
        ("🥦", "broccoli"),
        ("🧄", "garlic"),
        ("🧅", "onion"),
        ("🍄", "mushroom"),
        ("🥜", "peanuts"),
        ("🫘", "beans"),
        ("🌰", "chestnut"),
        ("🍞", "bread"),
        ("🥐", "croissant"),
        ("🥖", "baguette bread"),
        ("🫓", "flatbread"),
        ("🥨", "pretzel"),
        ("🥯", "bagel"),
        ("🥞", "pancakes"),
        ("🧇", "waffle"),
        ("🧀", "cheese wedge"),
        ("🍖", "meat on bone"),
        ("🍗", "poultry leg"),
        ("🥩", "cut of meat"),
        ("🥓", "bacon"),
        # food-prepared
        ("🍔", "hamburger"),
        ("🍟", "french fries"),
        ("🍕", "pizza"),
        ("🌭", "hot dog"),
        ("🥪", "sandwich"),
        ("🌮", "taco"),
        ("🌯", "burrito"),
        ("🫔", "tamale"),
        ("🥙", "stuffed flatbread"),
        ("🧆", "falafel"),
        ("🥚", "egg"),
        ("🍳", "cooking"),
        ("🥘", "shallow pan of food"),
        ("🍲", "pot of food"),
        ("🫕", "fondue"),
        ("🥣", "bowl with spoon"),
        ("🥗", "green salad"),
        ("🍿", "popcorn"),
        ("🧈", "butter"),
        ("🧂", "salt"),
        ("🥫", "canned food"),
        # food-asian
        ("🍱", "bento box"),
        ("🍘", "rice cracker"),
        ("🍙", "rice ball"),
        ("🍚", "cooked rice"),
        ("🍛", "curry rice"),
        ("🍜", "steaming bowl"),
        ("🍝", "spaghetti"),
        ("🍠", "roasted sweet potato"),
        ("🍢", "oden"),
        ("🍣", "sushi"),
        ("🍤", "fried shrimp"),
        ("🍥", "fish cake with swirl"),
        ("🥮", "moon cake"),
        ("🍡", "dango"),
        ("🥟", "dumpling"),
        ("🥠", "fortune cookie"),
        ("🥡", "takeout box"),
        # food-marine
        ("🦀", "crab"),
        ("🦞", "lobster"),
        ("🦐", "shrimp"),
        ("🦑", "squid"),
        ("🦪", "oyster"),
        # food-sweet
        ("🍦", "soft ice cream"),
        ("🍧", "shaved ice"),
        ("🍨", "ice cream"),
        ("🍩", "doughnut"),
        ("🍪", "cookie"),
        ("🎂", "birthday cake"),
        ("🍰", "shortcake"),
        ("🧁", "cupcake"),
        ("🥧", "pie"),
        ("🍫", "chocolate bar"),
        ("🍬", "candy"),
        ("🍭", "lollipop"),
        ("🍮", "custard"),
        ("🍯", "honey pot"),
        # drink
        ("🍼", "baby bottle"),
        ("🥛", "glass of milk"),
        ("☕", "hot beverage"),
        ("🫖", "teapot"),
        ("🍵", "teacup without handle"),
        ("🍶", "sake"),
        ("🍾", "bottle with popping cork"),
        ("🍷", "wine glass"),
        ("🍸", "cocktail glass"),
        ("🍹", "tropical drink"),
        ("🍺", "beer mug"),
        ("🍻", "clinking beer mugs"),
        ("🥂", "clinking glasses"),
        ("🥃", "tumbler glass"),
        ("🫗", "pouring liquid"),
        ("🥤", "cup with straw"),
        ("🧋", "bubble tea"),
        ("🧃", "beverage box"),
        ("🧉", "mate"),
        ("🧊", "ice"),
        # dishware
        ("🥢", "chopsticks"),
        ("🍽️", "fork and knife with plate"),
        ("🍴", "fork and knife"),
        ("🥄", "spoon"),
        ("🫙", "jar"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "✈️ Travel & Places": [
        # place-map
        ("🗺️", "world map"),
        ("🧭", "compass"),
        # place-geographic
        ("🏔️", "snow-capped mountain"),
        ("⛰️", "mountain"),
        ("🌋", "volcano"),
        ("🗻", "mount fuji"),
        ("🏕️", "camping"),
        ("🏖️", "beach with umbrella"),
        ("🏜️", "desert"),
        ("🏝️", "desert island"),
        ("🏞️", "national park"),
        # place-building
        ("🏟️", "stadium"),
        ("🏛️", "classical building"),
        ("🏗️", "building construction"),
        ("🧱", "brick"),
        ("🪨", "rock"),
        ("🪵", "wood"),
        ("🛖", "hut"),
        ("🏘️", "houses"),
        ("🏚️", "derelict house"),
        ("🏠", "house"),
        ("🏡", "house with garden"),
        ("🏢", "office building"),
        ("🏣", "japanese post office"),
        ("🏤", "post office"),
        ("🏥", "hospital"),
        ("🏦", "bank"),
        ("🏨", "hotel"),
        ("🏩", "love hotel"),
        ("🏪", "convenience store"),
        ("🏫", "school"),
        ("🏬", "department store"),
        ("🏭", "factory"),
        ("🏯", "japanese castle"),
        ("🏰", "castle"),
        ("💒", "wedding"),
        ("🗼", "tokyo tower"),
        ("🗽", "statue of liberty"),
        # place-religious
        ("⛪", "church"),
        ("🕌", "mosque"),
        ("🛕", "hindu temple"),
        ("🕍", "synagogue"),
        ("⛩️", "shinto shrine"),
        ("🕋", "kaaba"),
        # place-other
        ("⛲", "fountain"),
        ("⛺", "tent"),
        ("🌁", "foggy"),
        ("🌃", "night with stars"),
        ("🏙️", "cityscape"),
        ("🌄", "sunrise over mountains"),
        ("🌅", "sunrise"),
        ("🌆", "cityscape at dusk"),
        ("🌇", "sunset"),
        ("🌉", "bridge at night"),
        ("♨️", "hot springs"),
        ("🎠", "carousel horse"),
        ("💈", "barber pole"),
        ("🎡", "ferris wheel"),
        ("🎢", "roller coaster"),
        ("🏪", "convenience store"),
        # transport-ground
        ("🚂", "locomotive"),
        ("🚃", "railway car"),
        ("🚄", "high-speed train"),
        ("🚅", "bullet train"),
        ("🚆", "train"),
        ("🚇", "metro"),
        ("🚈", "light rail"),
        ("🚉", "station"),
        ("🚊", "tram"),
        ("🚝", "monorail"),
        ("🚞", "mountain railway"),
        ("🚋", "tram car"),
        ("🚌", "bus"),
        ("🚍", "oncoming bus"),
        ("🚎", "trolleybus"),
        ("🏎️", "racing car"),
        ("🚐", "minibus"),
        ("🚑", "ambulance"),
        ("🚒", "fire engine"),
        ("🚓", "police car"),
        ("🚔", "oncoming police car"),
        ("🚕", "taxi"),
        ("🚖", "oncoming taxi"),
        ("🚗", "automobile"),
        ("🚘", "oncoming automobile"),
        ("🚙", "sport utility vehicle"),
        ("🛻", "pickup truck"),
        ("🚚", "delivery truck"),
        ("🚛", "articulated lorry"),
        ("🚜", "tractor"),
        ("🏍️", "motorcycle"),
        ("🛵", "motor scooter"),
        ("🛺", "auto rickshaw"),
        ("🚲", "bicycle"),
        ("🛴", "kick scooter"),
        ("🛹", "skateboard"),
        ("🛼", "roller skate"),
        ("🚏", "bus stop"),
        ("🛣️", "motorway"),
        ("🛤️", "railway track"),
        ("⛽", "fuel pump"),
        ("🛞", "wheel"),
        ("🚨", "police car light"),
        ("🚥", "horizontal traffic light"),
        ("🚦", "vertical traffic light"),
        ("🛑", "stop sign"),
        ("⚓", "anchor"),
        # transport-water
        ("🛶", "canoe"),
        ("⛵", "sailboat"),
        ("🚤", "speedboat"),
        ("🛥️", "motor boat"),
        ("🛳️", "passenger ship"),
        ("⛴️", "ferry"),
        ("🚢", "ship"),
        # transport-air
        ("✈️", "airplane"),
        ("🛩️", "small airplane"),
        ("🛫", "airplane departure"),
        ("🛬", "airplane arrival"),
        ("🪂", "parachute"),
        ("💺", "seat"),
        ("🚁", "helicopter"),
        ("🚟", "suspension railway"),
        ("🚠", "mountain cableway"),
        ("🚡", "aerial tramway"),
        ("🛰️", "satellite"),
        ("🚀", "rocket"),
        ("🛸", "flying saucer"),
        # hotel
        ("🛎️", "bellhop bell"),
        ("🧳", "luggage"),
        # time
        ("⌛", "hourglass done"),
        ("⏳", "hourglass not done"),
        ("⌚", "watch"),
        ("⏰", "alarm clock"),
        ("⏱️", "stopwatch"),
        ("⏲️", "timer clock"),
        ("🕰️", "mantelpiece clock"),
        ("🕛", "twelve o clock"),
        ("🕧", "twelve-thirty"),
        ("🕐", "one o clock"),
        ("🕜", "one-thirty"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "⚽ Activities": [
        # event
        ("🎃", "jack-o-lantern"),
        ("🎄", "christmas tree"),
        ("🎆", "fireworks"),
        ("🎇", "sparkler"),
        ("🧨", "firecracker"),
        ("✨", "sparkles"),
        ("🎉", "party popper"),
        ("🎊", "confetti ball"),
        ("🎋", "tanabata tree"),
        ("🎍", "pine decoration"),
        ("🎎", "japanese dolls"),
        ("🎏", "carp streamer"),
        ("🎐", "wind chime"),
        ("🎑", "moon viewing ceremony"),
        ("🧧", "red envelope"),
        ("🎀", "ribbon"),
        ("🎁", "wrapped gift"),
        # award-medal
        ("🎗️", "reminder ribbon"),
        ("🎟️", "admission tickets"),
        ("🎫", "ticket"),
        ("🏆", "trophy"),
        ("🥇", "1st place medal"),
        ("🥈", "2nd place medal"),
        ("🥉", "3rd place medal"),
        ("🏅", "sports medal"),
        ("🎖️", "military medal"),
        # sport
        ("⚽", "soccer ball"),
        ("🏀", "basketball"),
        ("🏈", "american football"),
        ("⚾", "baseball"),
        ("🥎", "softball"),
        ("🎾", "tennis"),
        ("🏐", "volleyball"),
        ("🏉", "rugby football"),
        ("🥏", "flying disc"),
        ("🎱", "pool 8 ball"),
        ("🪀", "yo-yo"),
        ("🏓", "ping pong"),
        ("🏸", "badminton"),
        ("🏒", "ice hockey"),
        ("🏑", "field hockey"),
        ("🥍", "lacrosse"),
        ("🏏", "cricket game"),
        ("🪃", "boomerang"),
        ("🥅", "goal net"),
        ("⛳", "flag in hole"),
        ("🪁", "bow and arrow"),
        ("🏹", "bow and arrow"),
        ("🎣", "fishing pole"),
        ("🤿", "diving mask"),
        ("🥊", "boxing glove"),
        ("🥋", "martial arts uniform"),
        ("🎽", "running shirt"),
        ("🛹", "skateboard"),
        ("🛼", "roller skate"),
        ("🛷", "sled"),
        ("⛸️", "ice skate"),
        ("🏋️", "person lifting weights"),
        ("🤺", "person fencing"),
        ("⛷️", "skier"),
        ("🏂", "snowboarder"),
        ("🏊", "person swimming"),
        ("🏄", "person surfing"),
        ("🚣", "person rowing boat"),
        ("🧗", "person climbing"),
        ("🚵", "person mountain biking"),
        ("🚴", "person biking"),
        # game
        ("🏆", "trophy"),
        ("🎯", "bullseye"),
        ("🎮", "video game"),
        ("🕹️", "joystick"),
        ("🎲", "game die"),
        ("♟️", "chess pawn"),
        ("🎭", "performing arts"),
        ("🎨", "artist palette"),
        ("🖼️", "framed picture"),
        # arts-crafts
        ("🧵", "thread"),
        ("🪡", "spool of thread"),
        ("🧶", "yarn"),
        ("🪢", "knot"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "💡 Objects": [
        # clothing
        ("👓", "glasses"),
        ("🕶️", "sunglasses"),
        ("🥽", "goggles"),
        ("🦺", "safety vest"),
        ("👔", "necktie"),
        ("👕", "t-shirt"),
        ("👖", "jeans"),
        ("🧣", "scarf"),
        ("🧤", "gloves"),
        ("🧥", "coat"),
        ("🧦", "socks"),
        ("👗", "dress"),
        ("👘", "kimono"),
        ("🥻", "sari"),
        ("🩱", "one-piece swimsuit"),
        ("🩲", "briefs"),
        ("🩳", "shorts"),
        ("👙", "bikini"),
        ("👚", "womans clothes"),
        ("🪭", "folding hand fan"),
        ("👛", "purse"),
        ("👜", "handbag"),
        ("👝", "clutch bag"),
        ("🎒", "backpack"),
        ("🧳", "luggage"),
        ("👒", "womans hat"),
        ("🎩", "top hat"),
        ("🧢", "billed cap"),
        ("🪖", "military helmet"),
        ("⛑️", "rescue workers helmet"),
        ("💄", "lipstick"),
        ("💍", "ring"),
        ("💎", "gem stone"),
        # sound
        ("🔇", "muted speaker"),
        ("🔈", "speaker low volume"),
        ("🔉", "speaker medium volume"),
        ("🔊", "speaker high volume"),
        ("📢", "loudspeaker"),
        ("📣", "megaphone"),
        ("📯", "postal horn"),
        ("🔔", "bell"),
        ("🔕", "bell with slash"),
        # music
        ("🎼", "musical score"),
        ("🎵", "musical note"),
        ("🎶", "musical notes"),
        ("🎙️", "studio microphone"),
        ("🎚️", "level slider"),
        ("🎛️", "control knobs"),
        ("🎤", "microphone"),
        ("🎧", "headphone"),
        ("📻", "radio"),
        # musical-instrument
        ("🎷", "saxophone"),
        ("🪗", "accordion"),
        ("🎸", "guitar"),
        ("🎹", "musical keyboard"),
        ("🎺", "trumpet"),
        ("🎻", "violin"),
        ("🪕", "banjo"),
        ("🥁", "drum"),
        ("🪘", "long drum"),
        ("🪇", "maracas"),
        ("🪈", "flute"),
        # phone
        ("📱", "mobile phone"),
        ("📲", "mobile phone with arrow"),
        ("☎️", "telephone"),
        ("📞", "telephone receiver"),
        ("📟", "pager"),
        ("📠", "fax machine"),
        # computer
        ("🔋", "battery"),
        ("🪫", "low battery"),
        ("🔌", "electric plug"),
        ("💻", "laptop"),
        ("🖥️", "desktop computer"),
        ("🖨️", "printer"),
        ("⌨️", "keyboard"),
        ("🖱️", "computer mouse"),
        ("🖲️", "trackball"),
        ("💽", "computer disk"),
        ("💾", "floppy disk"),
        ("💿", "optical disk"),
        ("📀", "dvd"),
        ("🧮", "abacus"),
        # light-video
        ("🎥", "movie camera"),
        ("🎞️", "film frames"),
        ("📽️", "film projector"),
        ("🎬", "clapper board"),
        ("📺", "television"),
        ("📷", "camera"),
        ("📸", "camera with flash"),
        ("📹", "video camera"),
        ("📼", "videocassette"),
        ("🔍", "magnifying glass tilted left"),
        ("🔎", "magnifying glass tilted right"),
        ("🕯️", "candle"),
        ("💡", "light bulb"),
        ("🔦", "flashlight"),
        ("🏮", "red paper lantern"),
        ("🪔", "diya lamp"),
        # book-paper
        ("📔", "notebook with decorative cover"),
        ("📕", "closed book"),
        ("📖", "open book"),
        ("📗", "green book"),
        ("📘", "blue book"),
        ("📙", "orange book"),
        ("📚", "books"),
        ("📓", "notebook"),
        ("📒", "ledger"),
        ("📃", "page with curl"),
        ("📜", "scroll"),
        ("📄", "page facing up"),
        ("📰", "newspaper"),
        ("🗞️", "rolled-up newspaper"),
        ("📑", "bookmark tabs"),
        ("🔖", "bookmark"),
        ("🏷️", "label"),
        # money
        ("💰", "money bag"),
        ("🪙", "coin"),
        ("💴", "yen banknote"),
        ("💵", "dollar banknote"),
        ("💶", "euro banknote"),
        ("💷", "pound banknote"),
        ("💸", "money with wings"),
        ("💳", "credit card"),
        ("🧾", "receipt"),
        ("💹", "chart increasing with yen"),
        # mail
        ("📧", "e-mail"),
        ("📨", "incoming envelope"),
        ("📩", "envelope with arrow"),
        ("📤", "outbox tray"),
        ("📥", "inbox tray"),
        ("📦", "package"),
        ("📫", "closed mailbox with raised flag"),
        ("📪", "closed mailbox with lowered flag"),
        ("📬", "open mailbox with raised flag"),
        ("📭", "open mailbox with lowered flag"),
        ("📮", "postbox"),
        ("🗳️", "ballot box with ballot"),
        # writing
        ("✏️", "pencil"),
        ("✒️", "black nib"),
        ("🖋️", "fountain pen"),
        ("🖊️", "pen"),
        ("🖌️", "paintbrush"),
        ("🖍️", "crayon"),
        ("📝", "memo"),
        # office
        ("💼", "briefcase"),
        ("📁", "file folder"),
        ("📂", "open file folder"),
        ("🗂️", "card index dividers"),
        ("📅", "calendar"),
        ("📆", "tear-off calendar"),
        ("🗒️", "spiral notepad"),
        ("🗓️", "spiral calendar"),
        ("📇", "card index"),
        ("📈", "chart increasing"),
        ("📉", "chart decreasing"),
        ("📊", "bar chart"),
        ("📋", "clipboard"),
        ("📌", "pushpin"),
        ("📍", "round pushpin"),
        ("📎", "paperclip"),
        ("🖇️", "linked paperclips"),
        ("📏", "straight ruler"),
        ("📐", "triangular ruler"),
        ("✂️", "scissors"),
        ("🗃️", "card file box"),
        ("🗄️", "file cabinet"),
        ("🗑️", "wastebasket"),
        # lock
        ("🔒", "locked"),
        ("🔓", "unlocked"),
        ("🔏", "locked with pen"),
        ("🔐", "locked with key"),
        ("🔑", "key"),
        ("🗝️", "old key"),
        # tool
        ("🔨", "hammer"),
        ("🪓", "axe"),
        ("⛏️", "pick"),
        ("⚒️", "hammer and pick"),
        ("🛠️", "hammer and wrench"),
        ("🗡️", "dagger"),
        ("⚔️", "crossed swords"),
        ("🛡️", "shield"),
        ("🪚", "carpentry saw"),
        ("🔧", "wrench"),
        ("🪛", "screwdriver"),
        ("🔩", "nut and bolt"),
        ("⚙️", "gear"),
        ("🗜️", "clamp"),
        ("⚖️", "balance scale"),
        ("🦯", "white cane"),
        ("🔗", "link"),
        ("⛓️", "chains"),
        ("🪝", "hook"),
        ("🧲", "magnet"),
        ("🪜", "ladder"),
        # science
        ("⚗️", "alembic"),
        ("🔭", "telescope"),
        ("🔬", "microscope"),
        ("🩻", "x-ray"),
        ("💊", "pill"),
        ("🩹", "adhesive bandage"),
        ("🩺", "stethoscope"),
        ("🩼", "crutch"),
        ("🩸", "drop of blood"),
        ("🧬", "dna"),
        ("🧪", "test tube"),
        ("🧫", "petri dish"),
        ("🧯", "fire extinguisher"),
        # household
        ("🛒", "shopping cart"),
        ("🚪", "door"),
        ("🛗", "elevator"),
        ("🪞", "mirror"),
        ("🪟", "window"),
        ("🛏️", "bed"),
        ("🛋️", "couch and lamp"),
        ("🪑", "chair"),
        ("🚽", "toilet"),
        ("🪠", "plunger"),
        ("🚿", "shower"),
        ("🛁", "bathtub"),
        ("🪤", "mouse trap"),
        ("🪒", "razor"),
        ("🧴", "lotion bottle"),
        ("🧷", "safety pin"),
        ("🧹", "broom"),
        ("🧺", "basket"),
        ("🧻", "roll of paper"),
        ("🪣", "bucket"),
        ("🧼", "soap"),
        ("🫧", "bubbles"),
        ("🪥", "toothbrush"),
        ("🧽", "sponge"),
        ("🧯", "fire extinguisher"),
        ("🛒", "shopping cart"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "🔣 Symbols": [
        # transport-sign
        ("🚮", "litter in bin sign"),
        ("🚰", "potable water"),
        ("♿", "wheelchair symbol"),
        ("🚹", "mens room"),
        ("🚺", "womens room"),
        ("🚻", "restroom"),
        ("🚼", "baby symbol"),
        ("🚾", "water closet"),
        ("🛂", "passport control"),
        ("🛃", "customs"),
        ("🛄", "baggage claim"),
        ("🛅", "left luggage"),
        # warning
        ("⚠️", "warning"),
        ("🚸", "children crossing"),
        ("⛔", "no entry"),
        ("🚫", "prohibited"),
        ("🚳", "no bicycles"),
        ("🚭", "no smoking"),
        ("🚯", "no littering"),
        ("🚱", "non-potable water"),
        ("🚷", "no pedestrians"),
        ("📵", "no mobile phones"),
        ("🔞", "no one under eighteen"),
        ("☢️", "radioactive"),
        ("☣️", "biohazard"),
        # arrow
        ("⬆️", "up arrow"),
        ("↗️", "up-right arrow"),
        ("➡️", "right arrow"),
        ("↘️", "down-right arrow"),
        ("⬇️", "down arrow"),
        ("↙️", "down-left arrow"),
        ("⬅️", "left arrow"),
        ("↖️", "up-left arrow"),
        ("↕️", "up-down arrow"),
        ("↔️", "left-right arrow"),
        ("↩️", "right arrow curving left"),
        ("↪️", "left arrow curving right"),
        ("⤴️", "right arrow curving up"),
        ("⤵️", "right arrow curving down"),
        ("🔃", "clockwise vertical arrows"),
        ("🔄", "counterclockwise arrows button"),
        ("🔙", "back arrow"),
        ("🔚", "end arrow"),
        ("🔛", "on arrow"),
        ("🔜", "soon arrow"),
        ("🔝", "top arrow"),
        # religion
        ("🛐", "place of worship"),
        ("⚛️", "atom symbol"),
        ("🕉️", "om"),
        ("✡️", "star of david"),
        ("☸️", "wheel of dharma"),
        ("☯️", "yin yang"),
        ("✝️", "latin cross"),
        ("☦️", "orthodox cross"),
        ("☪️", "star and crescent"),
        ("☮️", "peace symbol"),
        ("🕎", "menorah"),
        ("🔯", "dotted six-pointed star"),
        ("🪯", "khanda"),
        # zodiac
        ("♈", "aries"),
        ("♉", "taurus"),
        ("♊", "gemini"),
        ("♋", "cancer"),
        ("♌", "leo"),
        ("♍", "virgo"),
        ("♎", "libra"),
        ("♏", "scorpio"),
        ("♐", "sagittarius"),
        ("♑", "capricorn"),
        ("♒", "aquarius"),
        ("♓", "pisces"),
        ("⛎", "ophiuchus"),
        # av-symbol
        ("🔀", "shuffle tracks button"),
        ("🔁", "repeat button"),
        ("🔂", "repeat single button"),
        ("▶️", "play button"),
        ("⏩", "fast-forward button"),
        ("⏭️", "next track button"),
        ("⏯️", "play or pause button"),
        ("◀️", "reverse button"),
        ("⏪", "fast reverse button"),
        ("⏮️", "last track button"),
        ("🔼", "upwards button"),
        ("⏫", "fast up button"),
        ("🔽", "downwards button"),
        ("⏬", "fast down button"),
        ("⏸️", "pause button"),
        ("⏹️", "stop button"),
        ("⏺️", "record button"),
        ("🎦", "cinema"),
        ("🔅", "dim button"),
        ("🔆", "bright button"),
        ("📶", "antenna bars"),
        ("🛜", "wireless"),
        ("📳", "vibration mode"),
        ("📴", "mobile phone off"),
        # gender
        ("♀️", "female sign"),
        ("♂️", "male sign"),
        ("⚧️", "transgender symbol"),
        # math
        ("✖️", "multiply"),
        ("➕", "plus"),
        ("➖", "minus"),
        ("➗", "divide"),
        ("🟰", "heavy equals sign"),
        ("♾️", "infinity"),
        # punctuation
        ("‼️", "double exclamation mark"),
        ("⁉️", "exclamation question mark"),
        ("❓", "red question mark"),
        ("❔", "white question mark"),
        ("❕", "white exclamation mark"),
        ("❗", "red exclamation mark"),
        ("〰️", "wavy dash"),
        # currency
        ("💱", "currency exchange"),
        ("💲", "heavy dollar sign"),
        # other-symbol
        ("⚕️", "medical symbol"),
        ("♻️", "recycling symbol"),
        ("⚜️", "fleur-de-lis"),
        ("🔱", "trident emblem"),
        ("📛", "name badge"),
        ("🔰", "japanese symbol for beginner"),
        ("⭕", "hollow red circle"),
        ("✅", "check mark button"),
        ("☑️", "check box with check"),
        ("✔️", "check mark"),
        ("❎", "cross mark button"),
        ("❌", "cross mark"),
        ("〽️", "part alternation mark"),
        ("✳️", "eight-spoked asterisk"),
        ("✴️", "eight-pointed star"),
        ("❇️", "sparkle"),
        ("©️", "copyright"),
        ("®️", "registered"),
        ("™️", "trade mark"),
        # keycap
        ("🔟", "keycap 10"),
        ("🔢", "input numbers"),
        ("🔡", "input lowercase letters"),
        ("🔠", "input uppercase letters"),
        # alphanum
        ("🅰️", "a button blood type"),
        ("🆎", "ab button blood type"),
        ("🅱️", "b button blood type"),
        ("🆑", "cl button"),
        ("🆒", "cool button"),
        ("🆓", "free button"),
        ("ℹ️", "information"),
        ("🆔", "id button"),
        ("Ⓜ️", "circled m"),
        ("🆕", "new button"),
        ("🆖", "ng button"),
        ("🅾️", "o button blood type"),
        ("🆗", "ok button"),
        ("🅿️", "p button"),
        ("🆘", "sos button"),
        ("🆙", "up button"),
        ("🆚", "vs button"),
        ("🈳", "japanese vacancy button"),
        ("🈹", "japanese discount button"),
        # geometric
        ("🔴", "red circle"),
        ("🟠", "orange circle"),
        ("🟡", "yellow circle"),
        ("🟢", "green circle"),
        ("🔵", "blue circle"),
        ("🟣", "purple circle"),
        ("🟤", "brown circle"),
        ("⚫", "black circle"),
        ("⚪", "white circle"),
        ("🟥", "red square"),
        ("🟧", "orange square"),
        ("🟨", "yellow square"),
        ("🟩", "green square"),
        ("🟦", "blue square"),
        ("🟪", "purple square"),
        ("🟫", "brown square"),
        ("⬛", "black large square"),
        ("⬜", "white large square"),
        ("◼️", "black medium square"),
        ("◻️", "white medium square"),
        ("◾", "black medium-small square"),
        ("◽", "white medium-small square"),
        ("▪️", "black small square"),
        ("▫️", "white small square"),
        ("🔶", "large orange diamond"),
        ("🔷", "large blue diamond"),
        ("🔸", "small orange diamond"),
        ("🔹", "small blue diamond"),
        ("🔺", "red triangle pointed up"),
        ("🔻", "red triangle pointed down"),
        ("💠", "diamond with a dot"),
        ("🔘", "radio button"),
        ("🔳", "white square button"),
        ("🔲", "black square button"),
    ],

    # ─────────────────────────────────────────────────────────────────────────
    "🚩 Flags": [
        ("🏁", "chequered flag"),
        ("🚩", "triangular flag"),
        ("🎌", "crossed flags"),
        ("🏴", "black flag"),
        ("🏳️", "white flag"),
        ("🏳️‍🌈", "rainbow flag"),
        ("🏳️‍⚧️", "transgender flag"),
        ("🏴‍☠️", "pirate flag"),
        # country flags (major)
        ("🇺🇸", "united states flag"),
        ("🇬🇧", "united kingdom flag"),
        ("🇨🇦", "canada flag"),
        ("🇦🇺", "australia flag"),
        ("🇩🇪", "germany flag"),
        ("🇫🇷", "france flag"),
        ("🇪🇸", "spain flag"),
        ("🇮🇹", "italy flag"),
        ("🇯🇵", "japan flag"),
        ("🇨🇳", "china flag"),
        ("🇰🇷", "south korea flag"),
        ("🇮🇳", "india flag"),
        ("🇧🇷", "brazil flag"),
        ("🇲🇽", "mexico flag"),
        ("🇷🇺", "russia flag"),
        ("🇳🇱", "netherlands flag"),
        ("🇸🇪", "sweden flag"),
        ("🇳🇴", "norway flag"),
        ("🇩🇰", "denmark flag"),
        ("🇫🇮", "finland flag"),
        ("🇵🇱", "poland flag"),
        ("🇺🇦", "ukraine flag"),
        ("🇹🇷", "turkey flag"),
        ("🇸🇦", "saudi arabia flag"),
        ("🇦🇪", "united arab emirates flag"),
        ("🇮🇩", "indonesia flag"),
        ("🇵🇭", "philippines flag"),
        ("🇹🇭", "thailand flag"),
        ("🇻🇳", "vietnam flag"),
        ("🇵🇰", "pakistan flag"),
        ("🇧🇩", "bangladesh flag"),
        ("🇿🇦", "south africa flag"),
        ("🇳🇬", "nigeria flag"),
        ("🇪🇬", "egypt flag"),
        ("🇦🇷", "argentina flag"),
        ("🇨🇱", "chile flag"),
        ("🇨🇴", "colombia flag"),
        ("🇵🇪", "peru flag"),
        ("🇨🇿", "czechia flag"),
        ("🇷🇴", "romania flag"),
        ("🇭🇺", "hungary flag"),
        ("🇬🇷", "greece flag"),
        ("🇵🇹", "portugal flag"),
        ("🇧🇪", "belgium flag"),
        ("🇨🇭", "switzerland flag"),
        ("🇦🇹", "austria flag"),
        ("🇮🇱", "israel flag"),
        ("🇸🇬", "singapore flag"),
        ("🇭🇰", "hong kong flag"),
        ("🇳🇿", "new zealand flag"),
        ("🇮🇷", "iran flag"),
        ("🇮🇶", "iraq flag"),
        ("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "england flag"),
        ("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "scotland flag"),
        ("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "wales flag"),
    ],
}


# Flat shortcode → emoji map (superset of what's in main.py)
SHORTCODE_MAP = {
    ":smile:": "😊", ":grin:": "😁", ":joy:": "😂", ":rofl:": "🤣",
    ":lol:": "😂", ":blush:": "😊", ":wink:": "😉", ":heart_eyes:": "😍",
    ":kissing_heart:": "😘", ":yum:": "😋", ":sunglasses:": "😎",
    ":thinking:": "🤔", ":neutral_face:": "😐", ":expressionless:": "😑",
    ":unamused:": "😒", ":cry:": "😢", ":sob:": "😭", ":angry:": "😠",
    ":rage:": "😡", ":triumph:": "😤", ":skull:": "💀", ":ghost:": "👻",
    ":robot:": "🤖", ":poop:": "💩", ":clown:": "🤡", ":confused:": "😕",
    ":sweat_smile:": "😅", ":sweat:": "😓", ":hushed:": "😯",
    ":heart:": "❤️", ":orange_heart:": "🧡", ":yellow_heart:": "💛",
    ":green_heart:": "💚", ":blue_heart:": "💙", ":purple_heart:": "💜",
    ":black_heart:": "🖤", ":broken_heart:": "💔", ":100:": "💯",
    ":thumbsup:": "👍", ":-1:": "👎", ":thumbsdown:": "👎",
    ":+1:": "👍", ":ok_hand:": "👌", ":wave:": "👋", ":clap:": "👏",
    ":pray:": "🙏", ":muscle:": "💪", ":eyes:": "👀", ":fire:": "🔥",
    ":star:": "⭐", ":sparkles:": "✨", ":zap:": "⚡", ":tada:": "🎉",
    ":party:": "🎉", ":gift:": "🎁", ":trophy:": "🏆", ":rocket:": "🚀",
    ":check:": "✅", ":x:": "❌", ":yes:": "✅", ":no:": "🚫",
    ":gg:": "🎮", ":cat:": "🐱", ":dog:": "🐶", ":pizza:": "🍕",
    ":coffee:": "☕", ":rainbow:": "🌈", ":snowflake:": "❄️",
    ":warning:": "⚠️", ":info:": "ℹ️", ":question:": "❓",
    ":exclamation:": "❗", ":recycle:": "♻️", ":peace:": "☮️",
    ":cross:": "✝️", ":sos:": "🆘", ":new:": "🆕", ":cool:": "🆒",
    ":free:": "🆓", ":up:": "🆙", ":ok:": "🆗", ":vs:": "🆚",
    ":red_circle:": "🔴", ":blue_circle:": "🔵", ":green_circle:": "🟢",
    ":yellow_circle:": "🟡", ":white_circle:": "⚪", ":black_circle:": "⚫",
    ":soccer:": "⚽", ":basketball:": "🏀", ":football:": "🏈",
    ":baseball:": "⚾", ":tennis:": "🎾", ":golf:": "⛳",
    ":video_game:": "🎮", ":dice:": "🎲", ":dart:": "🎯",
    ":art:": "🎨", ":musical_note:": "🎵", ":guitar:": "🎸",
    ":microphone:": "🎤", ":headphones:": "🎧", ":speaker:": "🔊",
    ":mute:": "🔇", ":bell:": "🔔", ":no_bell:": "🔕",
    ":phone:": "📱", ":computer:": "💻", ":camera:": "📷",
    ":tv:": "📺", ":radio:": "📻", ":mailbox:": "📫",
    ":envelope:": "📧", ":pencil:": "✏️", ":book:": "📖",
    ":books:": "📚", ":money:": "💰", ":credit_card:": "💳",
    ":key:": "🔑", ":lock:": "🔒", ":unlock:": "🔓",
    ":hammer:": "🔨", ":wrench:": "🔧", ":gear:": "⚙️",
    ":pill:": "💊", ":syringe:": "💉", ":microscope:": "🔬",
    ":telescope:": "🔭", ":bulb:": "💡", ":battery:": "🔋",
    ":house:": "🏠", ":car:": "🚗", ":airplane:": "✈️",
    ":ship:": "🚢", ":train:": "🚂", ":bus:": "🚌",
    ":bike:": "🚲", ":ambulance:": "🚑", ":police_car:": "🚓",
    ":earth:": "🌍", ":sun:": "☀️", ":moon:": "🌙",
    ":cloud:": "☁️", ":umbrella:": "☂️", ":snow:": "❄️",
    ":lightning:": "⚡", ":tornado:": "🌪️", ":wave_water:": "🌊",
    ":rose:": "🌹", ":tulip:": "🌷", ":sunflower:": "🌻",
    ":apple:": "🍎", ":banana:": "🍌", ":grapes:": "🍇",
    ":burger:": "🍔", ":fries:": "🍟", ":taco:": "🌮",
    ":sushi:": "🍣", ":cake:": "🎂", ":cookie:": "🍪",
    ":beer:": "🍺", ":wine:": "🍷", ":tea:": "🍵",
    ":japan:": "🇯🇵", ":us:": "🇺🇸", ":uk:": "🇬🇧",
    ":flag_white:": "🏳️", ":flag_black:": "🏴", ":gay_pride:": "🏳️‍🌈",
    ":pirate:": "🏴‍☠️",
}
